
#' co2_historical
#'
#' Historical annual mean CO2 concentration (in parts per million) from NOAA https://gml.noaa.gov/ccgg/trends/global.html
#'
#' @source ftp://aftp.cmdl.noaa.gov/products/trends/co2/co2_annmean_mlo.txt
#' @examples
#' \dontrun{
#'  library(gaia);
#'  co2_historical <- gaia::co2_historical
#' }
"co2_historical"


#' co2_projection
#'
#' Projected global annual mean CO2 concentration (in parts per million) based on GCAM7 Reference scenario, which is aligned with RCP7.0. Obtained from running default GCAM7 Reference scenario. This is the default CO2 projection used in gaia. User can update the CO2 concentration if preferred by using the argument co2_proj from yield_impact function.
#'
#' @source https://gmd.copernicus.org/articles/12/677/2019/gmd-12-677-2019.html
#' @format R data frame
#' @examples
#' \dontrun{
#'  library(gaia);
#'  co2_projection <- gaia::co2_projection
#' }
"co2_projection"


#' agprodchange_ni_gcam7
#'
#' Agricultural productivity change (unitless) obtained from GCAM7 Reference scenario. This is the baseline APC that is used to calculate the climate impacted APC.
#'
#' @source https://jgcri.github.io/gcam-doc/inputs_supply.html
#' @format R data frame
#' @examples
#' \dontrun{
#'  library(gaia);
#'  agprodchange_ni_gcam7 <- gaia::agprodchange_ni_gcam7
#' }
"agprodchange_ni_gcam7"

#' agprodchange_ni_gcam6
#'
#' Agricultural productivity change (unitless) obtained from GCAM6 Reference scenario. This is the baseline APC that is used to calculate the climate impacted APC.
#'
#' @source https://jgcri.github.io/gcam-doc/inputs_supply.html
#' @format R data frame
#' @examples
#' \dontrun{
#'  library(gaia);
#'  agprodchange_ni_gcam6 <- gaia::agprodchange_ni_gcam6
#' }
"agprodchange_ni_gcam6"

#' coef_default
#'
#' Regression coefficients generated by \href{https://broom.tidymodels.org/}{`broom::tidy()`} for the regression model using gaia's example historical climate data, including estimate, standard error, statistic, p-value, for the 17 default crops supported by gaia.
#'
#' @source Regression coefficients derived by using the default historical WATCH climate data
#' @format R data frame
#' @examples
#' \dontrun{
#'  library(gaia);
#'  coef_default <- gaia::coef_default
#' }
"coef_default"

#' country_id
#'
#' Mapping of country ID, country name, and country ISO codes. This table can be used to identify countries based on their IDs in weighted climate files generated by the `gaia::weighted_climate` function. For mode details, see the \href{https://jgcri.github.io/gaia/articles/vignette.html#weighted_climate}{User Guide}.
#'
#' @source country ID and name mapping
#' @format R data frame
#' @examples
#' \dontrun{
#'  library(gaia);
#'  country_id <- gaia::country_id
#' }
"country_id"
